name: twenty

services:
  server:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    expose:
      - "3000"
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      REDIS_URL: redis://redis:6379
      SERVER_URL: https://crm-toca.wlonik.easypanel.host
      ENCRYPTION_KEY: fnVMy1hkSIlHh038U5GZGI+VFcA4tTeZeTw8fUZdqzw=
      APP_SECRET: 3dVJitoC9XFdktef1+3V/TNOE1J+1aBY
      TZ: America/Sao_Paulo
      STORAGE_TYPE: local
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 30
    restart: always

  worker:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      REDIS_URL: redis://redis:6379
      SERVER_URL: https://crm-toca.wlonik.easypanel.host
      ENCRYPTION_KEY: fnVMy1hkSIlHh038U5GZGI+VFcA4tTeZeTw8fUZdqzw=
      APP_SECRET: 3dVJitoC9XFdktef1+3V/TNOE1J+1aBY
      TZ: America/Sao_Paulo
      STORAGE_TYPE: local
      DISABLE_DB_MIGRATIONS: "true"
      DISABLE_CRON_JOBS_REGISTRATION: "true"
    depends_on:
      db: { condition: service_healthy }
      server: { condition: service_healthy }
    restart: always

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost -d postgres
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
  server-local-data:
